# Generated by Django 5.0.3 on 2024-04-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0002_alter_server_description_alter_server_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servermember',
            unique_together=set(),
        ),
    ]
