# Generated by Django 5.0.3 on 2024-04-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("realm", "0002_alter_server_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="image",
        ),
    ]
