name: ollama-webui

on:
  push:
    branches: [ "master" ]
  pull_request:
  branches: [ "master" ]

env:
  CORE_IMAGE_NAME: nnnxion/capy-world-core
  BIBOON_IMAGE_NAME: nnnxion/capy-world-biboon
  NGINX_IMAGE_NAME: nnnxion/capy-world-nginx
  REDIS_IMAGE_NAME: nnnxion/capy-world-redis
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DCK_PASS }}" | docker login -u "${{ secrets.DCK_USERNAME }}" --password-stdin

    - name: Build core service image
      run: docker build --target prod -t ${{ env.CORE_IMAGE_NAME }}:${{ env.TAG }} ./backend/core

    - name: Push core service image
      run: docker push ${{ env.CORE_IMAGE_NAME }}:${{ env.TAG }}

